---
skip_commits:
  files:
    - "benchmarks/**"
    - "examples/**"
    - "*.md"
install:
  - curl https://curl.se/ca/cacert.pem --output C:\Ruby%ruby_version%\cacert.pm
  - set SSL_CERT_FILE=C:\Ruby%ruby_version%\cacert.pem
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler -v '< 2.0'
  - bundle install
before_test:
  - ruby -v
  - gem -v
  - bundle -v
build: off
test_script:
  - bundle exec rake ci
environment:
  matrix:
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
matrix:
  allow_failures:
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
